### PR TITLE
Update casacore

### PR DESCRIPTION
**Pull request by jolopezl**
Fixes several reported crashes:

- https://github.com/CARTAvis/carta-backend/issues/909
- https://github.com/CARTAvis/carta-backend/issues/1051

### CODE REVIEW

**Comment by pford** [comment]
@ajm-asiaa this casa6 commit is tagged 6.5.0.4

**Review by pford — APPROVED** [review]

**Comment by ajm-asiaa** [comment]
I confirm that the `18-update-casacasacore` branch fixes issues #909 and #1051.

But I'm sorry to report that it appears to introduce a new issue; the `MomentTest.CheckConsistencyForBeamConvolutions` unit test now crashes on RHEL8 only.
Without ASAN flags the Unit Test gives a `Segmentation fault (core dumped)`.
With ASAN flags, the full crash log is: [rhel8-unit-test-crash.log](https://github.com/CARTAvis/carta-casacore/files/8416107/rhel8-unit-test-crash.log)

Maybe it is an unrelated problem and the Unit Test needs to be modified? 
Should I post it as a new issue and approve this PR because this PR fixes the original issues?
 
If you want to test it, here is a Dockerfile for Almalinux (without ASAN) that installs the `18-update-casacasacore` branch of carta-casacore and a carta-backend: [Dockerfile-Almalinux-test.txt](https://github.com/CARTAvis/carta-casacore/files/8417285/Dockerfile-Almalinux-test.txt) 
(I needed to append .txt at the end so that I could upload it to Github)
You can run it, for example, as
```
docker build -f Dockerfile-Almalinux-test  -t test .
docker run -ti test
cd /root/carta-backend/test
./carta_backend_tests
./carta_backend_tests --gtest_filter=MomentTest.CheckConsistencyForBeamConvolutions
```

**Comment by pford** [comment]
@ajm-asiaa I tested this with the `rhel8-jenkins-mar2022` container I already had, and reproduced the crash.  Long story short there was no FFTW library installed.  Once I ran `yum install fftw fftw-devel` as shown on the casacore README, the test passed.  I do not see fftw in the install list on your attached Dockerfile either.

**Comment by ajm-asiaa** [comment]
@pford Thank you for figuring that out! I'm very sorry about the trouble. I'm surprised the casacore CMakeLists.txt does not ensure that dependency is present before building. But I'll make sure it is installed when I produce the new carta-casacore RPMs.

**Review by ajm-asiaa — APPROVED** [review]

**Pull request merged**
