### PR TITLE
Update casa6 master

### PR DESCRIPTION
**Pull request by pford**
Updates the casa6 commit to the latest master including carta-related PRs.  Includes updating casacore to Sept 9 commit 5d29aa3. The carta-backend builds with this update.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@pford It builds fine and works on CentOS7, Ubuntu, and MacOS. But is the regex issue fixed?
I'm asking because @kswang1029 provided me some test files, and it seems a carta_backend built using this carta-casacore branch still reports an error message when loading a region file (polygon_400.crtf) with a long region syntax. 
```Exception:   Illegal polygon specification [[450.975pix, 254.149pix],.```

Here are the files:
[gaussian.fits](http://alma.asiaa.sinica.edu.tw/_downloads/gaussian.fits)
[polygon_10.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_10.crtf)
[polygone_400.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_400.crtf)

**Comment by ajm-asiaa** [comment]
This is more of a bug between casacore and the Fortran compiler version rather than carta-casacore. I'll just mention it here as it might crop up in the near future. 

I notice on MacOS when using gfortran 10.2, I get this build error:

```[ 40%] Building Fortran object casa6/casatools/casacore/scimath_f/CMakeFiles/casa_scimath_f.dir/dfftpak.f.o
f951: Warning: Nonexistent include directory '/opt/casa/03/include' [-Wmissing-include-dirs]
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:732:72:

  732 |       CALL DRFTB1 (N,R,WSAVE,WSAVE(N+1),WSAVE(2*N+1))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:214:72:

  214 |       CALL DRFTF1 (N,R,WSAVE,WSAVE(N+1),WSAVE(2*N+1))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:82:72:

   82 |       CALL DRFTI1 (N,WSAVE(N+1),WSAVE(2*N+1))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:1284:72:

 1284 |       CALL DEFFT1 (N,WSAVE(2*N+1),WSAVE(3*N+1))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:2213:72:

 2213 |       CALL DCFTI1 (N,WSAVE(IW1),WSAVE(IW2))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:2341:72:

 2341 |       CALL DCFTF1 (N,C,WSAVE,WSAVE(IW1),WSAVE(IW2))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
/Users/acdc/carta-casacore/casa6/casatools/casacore/scimath_f/dfftpak.f:2806:72:

 2806 |       CALL DCFTB1 (N,C,WSAVE,WSAVE(IW1),WSAVE(IW2))
      |                                                                        1
Error: Type mismatch in argument 'ifac' at (1); passed REAL(8) to INTEGER(4)
make[2]: *** [casa6/casatools/casacore/scimath_f/CMakeFiles/casa_scimath_f.dir/dfftpak.f.o] Error 1
make[1]: *** [casa6/casatools/casacore/scimath_f/CMakeFiles/casa_scimath_f.dir/all] Error 2
make: *** [all] Error 2
```

That is using gfortran that currently comes with Homebrew gcc (`brew install gcc`): 
`GNU Fortran (Homebrew GCC 10.2.0) 10.2.0`
It can be fixed by installing gfortran directly from Homebrew instead (`brew install gfortran`). 
Luckily in this case it still uses an older version: 
`GNU Fortran (GCC) 8.2.0`
It builds successfully with this older version of gfortran.

**Comment by ajm-asiaa** [comment]
@pford There is also strange behavior with variant.h. It has been like this previously, and I think @veggiesaurus noticed it too. 

I'm just mentioning it as I see you changed some lines related to it in CMakeLists.txt, so maybe you were trying to fix it?

The problem is that when building in the cloned carta-casacore directory for the first time, and after the final `sudo make install` step, the file `carta-casacore/imageanalysis/variant.h` gets switched to "root" ownership.

That means if we were ever to try and run `make` again in the same directory, then we get the error:

> [ 65%] Built target casa_images
> cp: /Users/acdc/carta-casacore/imageanalysis/variant.h: Permission denied
> make[2]: *** [imageanalysis/CMakeFiles/modify_variant_h] Error 1
> make[1]: *** [imageanalysis/CMakeFiles/modify_variant_h.dir/all] Error 2
> make: *** [all] Error 2

We would either need to change the ownership of that file back to the user, or do `sudo make` instead. Is there any way to prevent the file ownership changing like that?

**Comment by markccchiang** [comment]
> @pford There is also strange behavior with variant.h. It has been like this previously, and I think @veggiesaurus noticed it too.
> 
> I'm just mentioning it as I see you changed some lines related to it in CMakeLists.txt, so maybe you were trying to fix it?
> 
> The problem is that when building in the cloned carta-casacore directory for the first time, and after the final `sudo make install` step, the file `carta-casacore/imageanalysis/variant.h` gets switched to "root" ownership.
> 
> That means if we were ever to try and run `make` again in the same directory, then we get the error:
> 
> > [ 65%] Built target casa_images
> > cp: /Users/acdc/carta-casacore/imageanalysis/variant.h: Permission denied
> > make[2]: *** [imageanalysis/CMakeFiles/modify_variant_h] Error 1
> > make[1]: *** [imageanalysis/CMakeFiles/modify_variant_h.dir/all] Error 2
> > make: *** [all] Error 2
> 
> We would either need to change the ownership of that file back to the user, or do `sudo make` instead. Is there any way to prevent the file ownership changing like that?

This problem is from my modification of the CMakeLists.txt. I will try to find a good way to solve it.

**Comment by pford** [comment]
> @pford It builds fine and works on CentOS7, Ubuntu, and MacOS. But is the regex issue fixed?
> I'm asking because @kswang1029 provided me some test files, and it seems a carta_backend built using this carta-casacore branch still reports an error message when loading a region file (polygon_400.crtf) with a long region syntax.
> `Exception: Illegal polygon specification [[450.975pix, 254.149pix],.`
> 
> Here are the files:
> [gaussian.fits](http://alma.asiaa.sinica.edu.tw/_downloads/gaussian.fits)
> [polygon_10.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_10.crtf)
> [polygone_400.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_400.crtf)

@ajm-asiaa the issue with polygon_400.crtf is that each point is on a different line, and the imageanalysis parser expects the region definition to be a single line.  Hence the error 
`Exception: Illegal polygon specification [[450.975pix, 254.149pix],.`

shows the specification as `[[450.975pix, 254.149pix],` because the parser takes this as the entire definition.

**Comment by ajm-asiaa** [comment]
> > @pford It builds fine and works on CentOS7, Ubuntu, and MacOS. But is the regex issue fixed?
> > I'm asking because @kswang1029 provided me some test files, and it seems a carta_backend built using this carta-casacore branch still reports an error message when loading a region file (polygon_400.crtf) with a long region syntax.
> > `Exception: Illegal polygon specification [[450.975pix, 254.149pix],.`
> > Here are the files:
> > [gaussian.fits](http://alma.asiaa.sinica.edu.tw/_downloads/gaussian.fits)
> > [polygon_10.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_10.crtf)
> > [polygone_400.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_400.crtf)
> 
> @ajm-asiaa the issue with polygon_400.crtf is that each point is on a different line, and the imageanalysis parser expects the region definition to be a single line. Hence the error
> `Exception: Illegal polygon specification [[450.975pix, 254.149pix],.`
> 
> shows the specification as `[[450.975pix, 254.149pix],` because the parser takes this as the entire definition.

@pford Thank you. I realise now that the `polygon_400.crtf` file from yesterday had bad formatting. Now I see it works fine using a [polygon_400.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_400.crtf) with correct formatting, and even a [polygon_500.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_500.crtf)
In fact, those region files also work with carta-backend's built using the old carta-casacore e.g. the v1.4 desktop release, so I must be incorrectly remembering how the regex issue affected the carta_backend before.

**Comment by ajm-asiaa** [comment]
Thanks to @kswang1029 for a 10000 point region file: [polygon_10000.crtf](http://alma.asiaa.sinica.edu.tw/_downloads/polygon_10000.crtf).
The good news is that it works on MacOS:
Screenshot 2020-10-21 at 09 19 53
(Moving the Editing region widget around on the screen is very slow though, but that is probably a frontend issue).

However, I can't get it to work on Linux versions (CentOS7 and Ubuntu) for some reason. On those systems it causes a segmentation fault in the backend. That is different than the previous problem e.g. in the v1.4 release where when loading such a large region file simply issued a warning in the frontend. I guess it shows that the carta-casacore regex issue is fixed and we may be seeing a new bug in the backend/frontend on Linux.

**Review by ajm-asiaa — APPROVED** [review]

**Comment by ajm-asiaa** [comment]
Here is an attempt using `gdb` on ubuntu to show the cause of the segmentation fault:

> Thread 1 "carta_backend" received signal SIGSEGV, Segmentation fault.
> 0x00007f4231590412 in std::__detail::_Executor<char const*, std::allocator<std::__cxx11::sub_match<char const*> >, std::__cxx11::regex_traits<char>, true>::_M_dfs(std::__detail::_Executor<char const*, std::allocator<std::__cxx11::sub_match<char const*> >, std::__cxx11::regex_traits<char>, true>::_Match_mode, long) () from /usr/local/lib/libcasa_casa.so.3
> (gdb)

**Comment by pford** [comment]
Closing for now until the regex issue for a polygon region #7 is fixed.

**Pull request closed without merging**
