### PR TITLE
Adding NO_SOVERSION=NO flag as proposed build flag in README

### PR DESCRIPTION
**Pull request by ajm-asiaa**
I think it would be good if we build the casacore library files with unique version string at the end e.g. `libcasa_scimath_f.so.2481.237.90` rather than `libcasa_scimath_f.so.3`

It would allow different carta_backend versions to work with different carta-casacore versions on the same machine.

To get it to work, we actually need to use two flags `-DCASA_BUILD=YES` and `-DNO_SOVERSION=NO`. 
I'm not sure, but hopefully `-DCASA_BUILD=YES` would not have any other side-effects? @pford ? 

It would be good for the CARTA Desktop releases, but not sure if it would be an advantage or disadvantage for the Ubuntu PPNs? @confluence ?

I propose we add `-DCASA_BUILD=YES -DNO_SOVERSION=NO` to the recommended build flags. What do you think?

### CODE REVIEW

**Comment by pford** [comment]
Darrell said CASA_BUILD=YES just sets all of the expected defaults for building casacore as part of a CASA/casatools build.  He did not indicate any side effects.  I built carta-casacore from source in my ubuntu 20.04 Docker with these flags and everything seems to be working.

**Review by pford — APPROVED** [review]

**Review by confluence — APPROVED** [review]
I can't think of any ways that this could cause an issue for the server version. If this has been tested and it works, it should be fine to merge. It's normal for a specific PPA version of a package to depend on a specific version of a dependency in the same PPA.

**Review by confluence — CHANGES_REQUESTED** [review]
Now that I'm more familiar with the configuration, I'm pretty sure that `NO_SOVERSION=NO` has no effect -- NO_SOVERSION controls whether there's *any* .so version, and the default is false (so yes, do include version information). What kind of version number is used is determined purely by the `CASA_BUILD` flag, as @pford says -- enabling that turns on long version numbers. Turning `CASA_BUILD` on also explicitly turns `NO_SOVERSION` off *again*, so we'd be doing it for a third time. :)

I have no strong opinion about what we should recommend as a default, but the packaged Ubuntu versions use the short .so numbers.

**Comment by ajm-asiaa** [comment]
Thanks. You are right! I just tried again and only adding ` -DCASA_BUILD=YES` is enough to get the long version numbers.

**Review by markccchiang — APPROVED** [review]

**Comment by confluence** [comment]
Closing after discussion with @ajm-asiaa .

**Pull request closed without merging**
