### PR TITLE
Add casadata autoupdate

### PR DESCRIPTION
**Pull request by jolopezl**
Moves auto-update script from carta-backend to carta-casacore.

### CODE REVIEW

**Review by confluence — APPROVED** [review]
I think that this is OK. It still uses a config file in `.carta` which will need to be symlinked to `.carta_beta`, but that's just a single file, which is more manageable. This is why I wanted this configuration check to be handled inside the backend -- but we can make that change later, since it's more complicated.

**Comment by ajm-asiaa** [comment]
Just one more change is needed. When I install it to `/opt` it is installed with root ownership: 
```
   8 -rwxr-xr-x  1 root    1928 Apr 21 17:18 measuresdata-update
   8 -rwxr-x---  1 root    4077 Apr 21 18:56 casa_data_autoupdate
  72 -rwxr-xr-x  1 root   35568 Apr 21 19:07 casahdf5support
```
So I am unable to execute it as my user `zsh: permission denied: ./casa_data_autoupdate`

Line 586 of CMakeLists.txt should add `OTHERS_EXECUTE` permissions.

**Comment by ajm-asiaa** [comment]
One other minor point. I tested it by uninstalling `wget`. It correctly switches to `curl` and downloads the data successfully.
```
CASA data has not been updated. CARTA will attempt to update automatically.
 ERROR: wget command not found
Trying curl
```
But I wonder if we should re-word it? 
It is not really an "ERROR" that wget is not present. 
The only error would be if both wget and curl are not present 
`            echo "ERROR: Please install $WGET or $CURL." >&2`

So maybe we could just say
`echo "$WGET command not found" >&2` and `echo "$CURL is not installed." >&2` ?

**Comment by confluence** [comment]
> But I wonder if we should re-word it? It is not really an "ERROR" that wget is not present. The only error would be if both wget and curl are not present ` echo "ERROR: Please install $WGET or $CURL." >&2`
> 
> So maybe we could just say `echo "$WGET command not found" >&2` and `echo "$CURL is not installed." >&2` ?

Good point -- I didn't catch that. I agree with the rewording suggestion.

**Review by ajm-asiaa — APPROVED** [review]
This appears to work exactly as planned.

If activated in `~/.carta/config/preferences.json` with, for example, 
```
    "auto_update_casa_data": true,
    "auto_update_casa_data_interval": 1,
```
then it will start downloading the WSRT_Measures.ztar file from astron.nl.
It will try to use `curl` first, and if curl is not present, it will use `wget`. 

I set the system clock forward in time in order to test the update interval part, it is appears to work fine. 

It extracts the geodetic and ephemerides folders to `~/.carta-casacore/data`.
I tried the carta_backend without `/usr/local/share/casacore/data` present, and it works perfectly.

For the carta-casacore debian/rules and RPM spec files, we will just need to remember to install`/opt/carta-casacore/bin/casa_data_autoupdate`.

Then for the carta-backend debian/rules and RPM spec files, we need to make sure to add `./opt/carta-casacore/bin/casa_data_autoupdate` to the `~/.carta` and `~/.carta-beta` scripts.

macOS Electron and AppImages will be slightly different and will need to have `casa_data_autoupdate` bundled inside.

**Comment by confluence** [comment]
Why patch this in the packages? Why not add it to the `carta` launcher in the backend repo? That is the script that is used by both Debian packages.

I suppose that the only problem is the location of the executable -- I was previously assuming that it would be installed to `/usr/bin/`, like the launcher script, so that it could be used with an unqualified name. Can we make that change? Then the base launcher in the repo wouldn't be relying on a carta-casacore package being installed in `opt`.

**Review by confluence — APPROVED** [review]
Sorry; I had forgotten that the `/opt/` location is set in the package configuration and all the files are placed in the same tree. So it looks like we will need to modify the packages anyway, even if it's to install the executable in `/usr/bin`.

**Comment by confluence** [comment]
My revised suggestion: 1) update the `carta` script in the backend repo to call the script (by its name) if it can be found; 2) have the carta-casacore package add a symlink from `/usr/bin` to the script location in `opt`.  This means that the casacore package is fully managing the installation of the script into a location which is on the path, and the backend doesn't have to be aware of the specifics. The script in the repo can then refer cleanly to the script command, expecting to find it on the path, and no special modifications to the backend packages (which use this launcher script) are required.

**Comment by ajm-asiaa** [comment]
I'm sorry, I made a typo last night. When I said:
> Then for the carta-backend debian/rules and RPM spec files, we need to make sure to add ./opt/carta-casacore/bin/casa_data_autoupdate to the ~/.carta and ~/.carta-beta scripts.

I actually meant the `carta` and `carta-beta` launchers. 

So the only difference from the previous plan to your suggestion 1  is the launcher scripts would try to run `./casa_data_autoupdate` from the $PATH and not the absolute path (`/opt/carta-casacore/bin/casa_data_autoupdate`). Then as per your suggestion 2, the carta-casacore debian/rules and RPM spec files would also create a symlink to `/opt/carta-casacore/bin/casa_data_autoupdate` in `/usr/bin`. Yes. That's a good idea!

**Comment by confluence** [comment]
> I actually meant the `carta` and `carta-beta` launchers.

Yes, I understand that you meant the launchers. My point is that these packages don't create custom launchers; they use the launcher script which is in the backend repository. That should be the default behaviour unless there is a special reason to use a custom launcher in a particular package. That is where I am suggesting that we make this addition. I will reopen the backend PR and follow up on this there.

**Comment by ajm-asiaa** [comment]
Maybe we didn't test this thoroughly enough. Did we consider what would happen if only `~/.carta-beta/config/preferences.json` existed?

At the moment, if `~/.carta` does not exist, the output is a little messy with `-gt: unary operator expected`, but it is not too bad. For example:
```
[root@5608ff46f0aa x86_64]# casa_data_autoupdate 
cat: /root/.carta/config/preferences.json: No such file or directory
cat: /root/.carta/config/preferences.json: No such file or directory
/usr/bin/casa_data_autoupdate: line 19: [: -gt: unary operator expected
AUTOUPDATE ENABLED = false
UPDATE INTERVAL = 7
CARTA will use the default ephemerides and geodetic data.
```
Now I realise it will not work if the user only uses or modifies `~/.carta-beta/config/preferences.json` because it only looks for `~/.carta/config/preferences.json`

But now could `casa_data_autoupdate` know if the user wants it to read from  `~/.carta-beta/config/preferences.json` or `~/.carta/config/preferences.json`? Unless it could detect if it is executed from `/usr/bin/carta` or `/usr/bin/carta-beta`?

Or maybe we shouldn't spend any more time on it? It is a very minor feature, and we could explain in the documentation that settings to control it should be put in `~/.carta/config/preferences.json`, even if using `carta-beta`. What do you think @confluence and @jolopezl?

**Comment by confluence** [comment]
I thought we had tested this with a symlink from `~/.carta-beta/config/preferences.json` to `~/.carta/config/preferences.json`. And also that the entire point of using this preference file rather than the backend preference file was to make the preference editable through the frontend GUI. I think that telling the user to make one symlink is simpler than telling them to hand-edit the preference file in a custom location.
 
This is only really relevant to RPM beta package users (since there is no reason for anyone to make use of this on Ubuntu because of availability of the KERN data package, which is the more standard way to keep the data up to date).

In future I really think that we should move this into the backend (and possibly expose the backend preferences through the frontend), which will eliminate this issue completely (since the backend will already be accessing the correct user directory).

**Pull request merged**
